# Generated by Django 4.2 on 2023-05-01 22:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ficha', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fichadog',
            name='data',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
