# Generated by Django 4.2 on 2023-05-06 02:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ficha', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='fichadog',
            name='nome_tutor',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
