# Generated by Django 4.2 on 2023-05-05 01:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Caixa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('relatorio_estadia', models.TextField(max_length=500)),
                ('desconto', models.DecimalField(decimal_places=2, max_digits=3)),
            ],
            options={
                'db_table': 'Caixa',
            },
        ),
        migrations.CreateModel(
            name='ServicosAdicionais',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_servico', models.CharField(max_length=50)),
                ('valor_servico', models.DecimalField(decimal_places=2, max_digits=6)),
                ('utilizado', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'Servicos_adicionais',
            },
        ),
    ]
