# Generated by Django 4.2 on 2023-05-05 01:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.db.models.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('hotel', '0001_initial'),
        ('caixa', '0001_initial'),
        ('ficha', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicosadicionais',
            name='num_reserva',
            field=models.ForeignKey(on_delete=django.db.models.fields.AutoField, to='hotel.reserva'),
        ),
        migrations.AddField(
            model_name='caixa',
            name='num_reserva',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='hotel.reserva'),
        ),
        migrations.AddField(
            model_name='caixa',
            name='pet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ficha.fichadog'),
        ),
        migrations.AddField(
            model_name='caixa',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
