# Generated by Django 4.2 on 2023-05-14 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caixa', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='caixa',
            name='desconto',
            field=models.DecimalField(decimal_places=1, max_digits=3),
        ),
    ]
