# Generated by Django 4.2 on 2023-05-15 01:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ficha', '0001_initial'),
        ('caixa', '0001_initial'),
        ('hotel', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='caixa',
            name='num_reserva',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='hotel.reserva'),
        ),
        migrations.AddField(
            model_name='caixa',
            name='pet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ficha.fichadog'),
        ),
    ]
