# Generated by Django 4.2 on 2023-05-16 05:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ficha', '0001_initial'),
        ('hotel', '0005_reserva_pago_reservaday_pago'),
        ('caixa', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CaixaDay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usuario', models.CharField(max_length=100)),
                ('relatorio_estadia', models.TextField(max_length=500)),
                ('desconto', models.DecimalField(decimal_places=1, max_digits=3)),
                ('num_reserva', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='hotel.reservaday')),
                ('pet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ficha.fichadog')),
            ],
            options={
                'db_table': 'CaixaDay',
            },
        ),
    ]
