# Generated by Django 4.2 on 2023-05-09 04:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0002_remove_reservaday_id_alter_reservaday_num_reserva'),
        ('caixa', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicosadicionais',
            name='num_reserva',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hotel.reserva'),
        ),
    ]
