# Generated by Django 4.2 on 2023-05-03 03:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ficha', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReservaDay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_entrada', models.DateField()),
                ('data_saida', models.DateField()),
                ('hora_entrada', models.TimeField()),
                ('horario_alimentacao', models.CharField(choices=[('2x_dia', 'Duas vezes por dia'), ('3x_dia', 'Três vezes por dia'), ('personalizado', 'Horário personalizado')], max_length=20)),
                ('horario_personalizado', models.CharField(blank=True, max_length=20, null=True)),
                ('instrucoes_medicamentos', models.CharField(blank=True, max_length=100, null=True)),
                ('servicos_adicionais', models.TextField(blank=True, max_length=100, null=True)),
                ('autorizacao_para_cuidados_medicos', models.BooleanField(choices=[(False, 'Não'), (True, 'Sim')], default=False)),
                ('dog', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ficha.fichadog')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'Reserva_Day',
            },
        ),
        migrations.CreateModel(
            name='Reserva',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_entrada', models.DateField()),
                ('data_saida', models.DateField()),
                ('hora_entrada', models.TimeField()),
                ('horario_alimentacao', models.CharField(choices=[('2x_dia', 'Duas vezes por dia'), ('3x_dia', 'Três vezes por dia'), ('personalizado', 'Horário personalizado')], max_length=20)),
                ('horario_personalizado', models.CharField(blank=True, max_length=20, null=True)),
                ('instrucoes_medicamentos', models.CharField(blank=True, max_length=100, null=True)),
                ('servicos_adicionais', models.TextField(blank=True, max_length=100, null=True)),
                ('autorizacao_para_cuidados_medicos', models.BooleanField(choices=[(False, 'Não'), (True, 'Sim')], default=False)),
                ('pet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ficha.fichadog')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'Reserva_Hotel',
            },
        ),
    ]
