# Generated by Django 4.2.1 on 2023-05-15 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reserva',
            name='pago',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
