# Generated by Django 4.2 on 2023-05-04 02:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reserva',
            name='num_reserva',
            field=models.IntegerField(auto_created=True, default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='reservaday',
            name='num_reserva',
            field=models.IntegerField(auto_created=True, default=1),
            preserve_default=False,
        ),
    ]
