# Generated by Django 4.2 on 2023-05-15 02:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='servicosadicionais',
            name='num_reserva',
        ),
        migrations.AlterField(
            model_name='reservaday',
            name='servicos_adicionais',
            field=models.ManyToManyField(blank=True, null=True, to='hotel.servicosadicionais'),
        ),
    ]
