# Generated by Django 4.2 on 2023-05-17 05:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0005_reserva_pago_reservaday_pago'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reserva',
            name='servicos_adicionais',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='hotel.servicosadicionais'),
        ),
    ]
